---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: default
lint:
  name: yamllint
platforms:
  - name: debian9-monitoring-plugins
    image: debian:10
    # command: /sbin/init
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
  - name: debian10-monitoring-plugins
    image: debian:9
    # command: /sbin/init
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        stage: docker
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
