---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: centos
lint:
  name: yamllint
platforms:
  - name: centos-icinga2-icingaweb2
    groups:
      - icinga2master
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        stage: docker
        icinga2_ticketsalt: aiSee1aan4etho4a
      icinga2master:
        icinga2_admin_email: not@available.invalid
        icinga2_idodb_name: icinga2
        icinga2_idodb_user: icinga2
        icinga2_idodb_pass: dbpass
        icingaweb_db_pass: webdbpass
        icingaweb_password_salt: eemoojee8dohl9eM
        icingaweb_admin_pass: password
        icingaweb_roles:
          - name: Testrole
            groups: Testgroup
            permissions: "module/grafana, module/monitoring, monitoring/command/schedule-check, monitoring/command/acknowledge-problem, monitoring/command/remove-acknowledgement, monitoring/command/comment/*, monitoring/command/comment/add, monitoring/command/downtime/*, monitoring/command/downtime/schedule, monitoring/command/downtime/delete"
            filter: "(host_name=*test*|host_name=test*)"

  lint:
    name: ansible-lint
    options:
      x:
        - skip_ansible_lint
verifier:
  name: testinfra
  lint:
    name: flake8
