---
- name: Prepare
  hosts: all
  become: true
  pre_tasks:
    - name: enable scl
      package:
        name: centos-release-scl
        state: installed

    - name: install prerequisites
      package:
        name:
          - mariadb-server
          - firewalld
          - rh-php72
          - rh-php72-php-pdo
          - httpd
        state: installed

    - name: enable services
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - firewalld
        - mariadb
        - httpd

  roles:
    - php-scl
