---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: default
lint:
  name: yamllint
platforms:
  - name: debian-icinga2-hostconfig-master
    groups:
      - icinga2master
    image: debian:10
    command: /sbin/init
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    privileged: True
  - name: debian-icinga2-hostconfig-client
    groups:
      - icinga2client
    image: debian:10
    command: /sbin/init
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    privileged: True
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        stage: docker
        icinga2_ticketsalt: aiSee1aan4etho4a
      icinga2master:
        icinga2_admin_email: not@available.invalid
        icinga2_idodb_pass: dbpass
      icinga2satellite:
        icinga_is_satellite: true
        icinga_zone: satellite
      icinga2satclient:
        icinga_parent:
          zone: satellite
          endpoints:
            - "{{ groups.icinga2satellite|first }}"
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
