---

- name: enable required repos
  yum:
    name:
      - epel-release
      - centos-release-scl
      - https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm
  when: ansible_distribution == "CentOS"

- name: install icinga2 and required packages
  yum:
    name:
      - icinga2
      - icinga2-ido-mysql
      - icinga2-selinux
      - mailx
      - MySQL-python
    state: present
    enablerepo: "{{ icinga2_repo }}"
  notify: restart icinga2
