---
- name: Prepare
  hosts: all
  become: true
  gather_subset:
    - '!all'
    - '!any'
    - network
  tasks:
    - name: Populate hosts file
      lineinfile:
        path: /etc/hosts
        line: '{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}'
        unsafe_writes: true
      loop: '{{ groups.all }}'

    - name: install prerequisites
      package:
        name:
          - firewalld
        state: present

    - name: enable services
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - firewalld

- name: Run master role to prepare master host
  hosts: icinga2master
  become: true
  gather_subset:
    - '!all'
    - '!any'
    - network
  pre_tasks:
    - name: install prerequisites
      package:
        name:
          - mariadb-server
        state: installed

    - name: enable services
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - mariadb
  roles:
    - role: icinga2-master
