---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: ubuntu
lint:
  name: yamllint
platforms:
  - name: icinga2-checks-ubuntu-bionic
    image: ubuntu:bionic
    command: /lib/systemd/systemd
    privileged: true
    groups:
      - icinga2master
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        stage: docker
        icinga2_ticketsalt: aiSee1aan4etho4a
      icinga2master:
        icinga2_admin_email: not@available.invalid
        icinga2_idodb_pass: dbpass
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
    ssh_connection:
      pipelining: true
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
