---
- name: Prepare
  hosts: all
  become: true
  pre_tasks:
    - name: install prerequisites
      package:
        name:
          - mariadb-server
          - firewalld
        state: present

    - name: enable services
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - firewalld
        - mariadb

  roles:
    - role: icinga2-master
