---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: install prerequisites
      package:
        name:
          - mariadb-server
          - firewalld
          - php7.3
          - php7.3-mysql
          - apache2
        state: installed

    - name: enable services
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - firewalld
        - mysql
        - apache2
