---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Gather limited facts for hosts file
      setup:
        gather_subset:
          - '!all'
          - '!any'
          - network

    - name: Populate hosts file
      lineinfile:
        path: /etc/hosts
        line: '{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}'
        unsafe_writes: true
      with_items: '{{ groups.all }}'

    - name: install prerequisites
      package:
        name:
          - mariadb-server
          - ufw
        state: present

    - name: enable services
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - ufw
        - mysql

- name: Run master role to prepare master host
  hosts: icinga2master
  become: true
  gather_subset:
    - '!all'
    - '!any'
    - network
  roles:
    - role: icinga2-master
