---
- name: enable required repos
  yum:
    name:
      - epel-release
      - centos-release-scl
      - https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm
  when: ansible_distribution == "CentOS"

- name: install icinga2
  yum:
    name:
      - icinga2
      - icinga2-selinux
    state: present
    enablerepo: "{{ icinga_repo }}"
  when: ansible_distribution_major_version > '6'
  notify: restart icinga2

- name: install icinga2 (no Icinga selinux policy available for EL 6)
  yum:
    name:
      - icinga2
    state: installed
    enablerepo: "{{ icinga_repo }}"
  when: ansible_distribution_major_version == '6'
  notify: restart icinga2
