---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: centos
lint:
  name: yamllint
platforms:
  - name: centos-monitoring-plugins
    image: centos:7
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        stage: docker
  lint:
    name: ansible-lint
